version: '3.6'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Dxo5MQaol4Lu74Wz2kX2ri9
      MYSQL_USER:     db_user
      MYSQL_PASSWORD: EfnyF4CYoGRTZMVT
      MYSQL_DATABASE: sampledb
    ports:
      - 10.52.221.2:3306:3306
    volumes:
      - /var/lib/mysql
      - ./docker/db:/etc/mysql/conf.d

  api:
    build:
      context: ./docker/api
      target: dev
    ports:
      - 10.52.221.1:80:80
    links:
      - db
    environment:
      - FQDN
      - PHP_TZ
      - SRC_DIR
      - COMPOSER_VENDOR_INSTALL
      - DB_MIGRATE
      - YII_ENV
      - YII_DEBUG
    volumes:
      - ./:/var/www/myapp
    depends_on:
      - db
    stdin_open: true
    tty: true